Merge the API into one file.
w3c/webrtc-rtptransport pull request #45
Opened 2024-06-03 09:42 UTC by Philipel-WebRTC

2024-06-03 10:35 UTC, tonyherre requested changes
Generally looks good, just would like to do the sendRtp rename separately

As discussed offline, we could potentially go straight to bikeshed and start building up a draft spec from that. Interested in what other reviewers think?

2024-06-03 10:35 UTC, tonyherre commented on api-outline.md
> +  void enqueueRtp(RtpPacket packet);
Renaming while otherwise just refactoring is a little confusing. Leave as is in the PR, and we can fix the overloading in #32?
I added a comment over there too on how I thought these would be merged.

2024-06-03 10:53 UTC, Philipel-WebRTC commented on api-outline.md
> +  void enqueueRtp(RtpPacket packet);
Right, I tried to do the minimal amount of refactoring when merging, but I could leave it as is and the problem would still be highlighted.

Updated.

2024-06-03 14:23 UTC, tonyherre approved these changes
Much nice, many combine. LGTM

2024-06-11 14:39 UTC, pthatcher reviewed
Merging fun to be had

2024-06-11 14:40 UTC, pthatcher approved these changes

2024-06-20 13:29 UTC, tonyherre commented
@aboba Could we merge this to unblock other the PRs working on top of it?
Was discussed & approved during the discussion last week.

2024-06-25 14:07 UTC, aboba approved these changes

2024-06-25 14:07 UTC, merged